// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ZrbQ-kp08K5PaF0AfydVwu75Mp-YSAI',
    appId: '1:874582571928:web:cfd3cfd2101b8d1a5809ed',
    messagingSenderId: '874582571928',
    projectId: 'xafe-backend',
    authDomain: 'xafe-backend.firebaseapp.com',
    storageBucket: 'xafe-backend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFQvVtdqhNG6GYnb3dywlYM6QjJUyiDiE',
    appId: '1:874582571928:android:360d41523376b3675809ed',
    messagingSenderId: '874582571928',
    projectId: 'xafe-backend',
    storageBucket: 'xafe-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLR1ODscWMYmZMHl0zG5WRAKt2Ivflung',
    appId: '1:874582571928:ios:600fd34fb891b1a75809ed',
    messagingSenderId: '874582571928',
    projectId: 'xafe-backend',
    storageBucket: 'xafe-backend.appspot.com',
    iosClientId: '874582571928-d0j7f84sa54tmd4o07ffn5cancquh477.apps.googleusercontent.com',
    iosBundleId: 'com.example.xafe',
  );
}
